"""Generate docs/data.js: edge list, layout coordinates and seed pools.

Setup and run, from the repo root:

    uv venv --python 3.13 .venv-kiosk
    uv pip install --python .venv-kiosk/bin/python numpy igraph
    uv run --no-project --python .venv-kiosk/bin/python tools/kiosk/build_data.py

Output goes to docs/ (not tools/) because GitHub Pages serves the repo root or
/docs only - Settings -> Pages -> Branch: main, Folder: /docs.

Seed pools are NOT recomputed from centrality - they are recovered from the
research's own pickled simulation output (sim_output/sims_*.dat), so the page
seeds from exactly the node sets the study used.
"""
import json, random, sys, time
import numpy as np
import igraph as ig

N = 4039
ROOT = '/Users/haidaralifawwaz/Documents/rumour-spread-model'

edges = np.loadtxt(f'{ROOT}/datasets/facebook_combined.txt', dtype=np.int32)
assert edges.shape == (88234, 2), edges.shape
src, dst = edges[:, 0].astype(np.int64), edges[:, 1].astype(np.int64)
assert src.min() >= 0 and max(src.max(), dst.max()) < N

deg = np.bincount(src, minlength=N) + np.bincount(dst, minlength=N)

pools = json.load(open('/tmp/seed_pools.json'))
top_bc = pools['sims_bc']
top_cc = pools['sims_cc']
deg_matched = pools['sims_deg_bc']   # degree-matched control for the Betweenness pool

print(f'n={N} edges={len(edges)} mean_deg={deg.mean():.1f}')
for name, pool in [('top_bc', top_bc), ('top_cc', top_cc), ('deg_matched', deg_matched)]:
    d = deg[pool]
    print(f'  {name}: n={len(pool)} mean_deg={d.mean():.1f} min={d.min()} max={d.max()}')

# ---- layout -------------------------------------------------------------
# Fruchterman-Reingold, 500 iterations. igraph's FR uses Python's `random`
# module, so seeding it makes the layout reproducible.
# (DRL was also tried; it produces long stringy edges with no visible
# community structure, so FR wins for a 2 m viewing distance.)
g = ig.Graph(n=N, edges=[(int(a), int(b)) for a, b in edges], directed=False)
random.seed(7)
t0 = time.time()
layout = g.layout_fruchterman_reingold(niter=500)
print(f'FR layout: {time.time() - t0:.1f}s')
xy = np.asarray(layout.coords, dtype=np.float64)

xmin, ymin = xy.min(axis=0)
xmax, ymax = xy.max(axis=0)
scale = 1000.0 / max(xmax - xmin, ymax - ymin)   # single scale -> aspect preserved
xy = (xy - [xmin, ymin]) * scale
xy = np.round(xy).astype(np.int32)
print(f'xy bbox: x {xy[:,0].min()}..{xy[:,0].max()}  y {xy[:,1].min()}..{xy[:,1].max()}')

# ---- emit ---------------------------------------------------------------
def flat(arr, per_line=40):
    a = [str(int(v)) for v in np.asarray(arr).ravel()]
    return ',\n    '.join(','.join(a[i:i + per_line]) for i in range(0, len(a), per_line))

out = f"""// data.js - generated by tools/kiosk/build_data.py. Do not edit by hand.
//
// Graph: SNAP ego-Facebook (4,039 nodes / 88,234 undirected edges).
// Seed pools are recovered from the study's own simulation output
// (sim_output/sims_*.dat), so the page seeds from the exact node sets the
// research used rather than re-deriving them from centrality.
//
// top_bc       top-30 betweenness nodes   (mean degree {deg[top_bc].mean():.1f})
// top_cc       top-30 closeness nodes     (mean degree {deg[top_cc].mean():.1f})
// deg_matched  degree-matched control for the Betweenness pool (mean degree {deg[deg_matched].mean():.1f})
window.GRAPH_DATA = {{
  n: {N},

  // flat undirected edge endpoints: [a0,b0, a1,b1, ...]
  edges: [
    {flat(edges)}
  ],

  // flat layout coordinates scaled to 0..1000, aspect ratio preserved
  xy: [
    {flat(xy)}
  ],

  top_bc: [{','.join(str(int(v)) for v in top_bc)}],
  top_cc: [{','.join(str(int(v)) for v in top_cc)}],
  deg_matched: [{','.join(str(int(v)) for v in deg_matched)}]
}};
"""
path = f'{ROOT}/docs/data.js'
open(path, 'w').write(out)
import os
print(f'wrote {path} ({os.path.getsize(path)/1024:.0f} KB)')
